### ISSUE TITLE
Hardcoded salt and IV

### ISSUE THREAD

**Issue by rpede** [mihnea-radulescu/passwordsecure#1]
Don't hard code salt and IV.

Generate a salt when master password is created such that each user will have a different salt.

Never reuse IV!
A new IV should be generated each time AccountEntryCollection is encrypted.

You can use [System.Security.Cryptography.RandomNumberGenerator](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator) to generate salt and IV.

Also, 16 iterations of PBKDF2 (Rfc2898DeriveBytes) is way too low.
See [OWASP - Password Storage Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2) for recommendations.

Consider adding an upgrade path for existing users.
I was about to write a pull request fixing the issues above, but realized that you break it for anyone that happens to use it.

Let me know if I can assist.

**Comment by mihnea-radulescu** [comment]
Hi @rpede,

Thank you very much for your thorough and well-considered feedback!

I can implement the suggested changes myself, and let you know when they are done. Alternatively, if you would like to submit a PR yourself, just let me know, and I will gladly review it.

Regarding updating existing encrypted files, I am thinking of some form of versioning, such that, when an older version of the encrypted file is being imported, with an implicit version of 1, it will then be saved in the new format, with an explicit version of 2.

The version could be added as a file header into the encrypted file, just before the actual encrypted content. The absence of such a header would indicate version 1. Based on the version determined, a specific implementation of IDataEncryptionService would be retrieved from an IDataEncryptionServiceFactory instance. For encryption, when saving the data, only the latest version of IDataEncryptionService would be used.

Perhaps it would make sense to pull the decryption method out the interface IDataEncryptionService into a separate IDataDecryptionService, then different implementation would only be needed for the IDataDecryptionService interface, since the encryption would only feature the latest version of the logic.

**Comment by rpede** [comment]
Created a pull-request with a quick implementation of an upgrade path as discussed.
Could perhaps use some refactoring.

**Comment by rpede** [comment]
Even a good password will have way less entropy than a 256 bit key. So an attacker would attempt to guess the password rather than the key. Making key derivation computationally expensive increase the cost per guess. Random salt prevents rainbow table attacks.

There is still a bit of a problem with the backup mechanism, since it keeps a copy old format around.
